/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotebooksIdRouteImport } from './routes/notebooks/$id'
import { Route as NotebooksNewRouteImport } from './routes/notebooks/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as NotebooksIdEditRouteImport } from './routes/notebooks/$id_.edit'
import { Route as ApiNotebooksIdExportRouteImport } from './routes/api/notebooks/$id.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIdRoute = NotebooksIdRouteImport.update({
  id: '/notebooks/$id',
  path: '/notebooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksNewRoute = NotebooksNewRouteImport.update({
  id: '/notebooks/new',
  path: '/notebooks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIdEditRoute = NotebooksIdEditRouteImport.update({
  id: '/notebooks/$id_/edit',
  path: '/notebooks/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotebooksIdExportRoute = ApiNotebooksIdExportRouteImport.update({
  id: '/api/notebooks/$id/export',
  path: '/api/notebooks/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/notebooks/new': typeof NotebooksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/notebooks/$id/edit': typeof NotebooksIdEditRoute
  '/api/notebooks/$id/export': typeof ApiNotebooksIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/notebooks/new': typeof NotebooksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/notebooks/$id/edit': typeof NotebooksIdEditRoute
  '/api/notebooks/$id/export': typeof ApiNotebooksIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/notebooks/new': typeof NotebooksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/notebooks/$id_/edit': typeof NotebooksIdEditRoute
  '/api/notebooks/$id/export': typeof ApiNotebooksIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/notebooks/$id'
    | '/notebooks/new'
    | '/api/auth/$'
    | '/notebooks/$id/edit'
    | '/api/notebooks/$id/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/notebooks/$id'
    | '/notebooks/new'
    | '/api/auth/$'
    | '/notebooks/$id/edit'
    | '/api/notebooks/$id/export'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/notebooks/$id'
    | '/notebooks/new'
    | '/api/auth/$'
    | '/notebooks/$id_/edit'
    | '/api/notebooks/$id/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  NotebooksIdRoute: typeof NotebooksIdRoute
  NotebooksNewRoute: typeof NotebooksNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  NotebooksIdEditRoute: typeof NotebooksIdEditRoute
  ApiNotebooksIdExportRoute: typeof ApiNotebooksIdExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$id': {
      id: '/notebooks/$id'
      path: '/notebooks/$id'
      fullPath: '/notebooks/$id'
      preLoaderRoute: typeof NotebooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/new': {
      id: '/notebooks/new'
      path: '/notebooks/new'
      fullPath: '/notebooks/new'
      preLoaderRoute: typeof NotebooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$id_/edit': {
      id: '/notebooks/$id_/edit'
      path: '/notebooks/$id/edit'
      fullPath: '/notebooks/$id/edit'
      preLoaderRoute: typeof NotebooksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notebooks/$id/export': {
      id: '/api/notebooks/$id/export'
      path: '/api/notebooks/$id/export'
      fullPath: '/api/notebooks/$id/export'
      preLoaderRoute: typeof ApiNotebooksIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  NotebooksIdRoute: NotebooksIdRoute,
  NotebooksNewRoute: NotebooksNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  NotebooksIdEditRoute: NotebooksIdEditRoute,
  ApiNotebooksIdExportRoute: ApiNotebooksIdExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
